/**
 * `pnpm data:publish [-- --city <slug>]`: upload a city's generated tiles (from
 * `pnpm data:build`) as a new GitHub release, and point its `tiles.lock.json` at it. Needs the
 * GitHub CLI, logged in with write access. Commit the lock afterwards. See DATA.md §9.
 */
import { execFileSync } from 'node:child_process';
import { join } from 'node:path';
import { parseArgs } from 'node:util';
import { contentRoot, loadCityPacks } from '@atlas/content';
import { writeJson } from './lib/io';
import { buildLock, generatedFiles, releaseTag } from './lib/tiles-release';
import { paths } from './step';

const { values } = parseArgs({
  args: process.argv.slice(2).filter((a) => a !== '--'),
  options: { city: { type: 'string' } },
});

const gh = (args: string[]) => execFileSync('gh', args, { encoding: 'utf8' }).trim();

const { packs, errors } = await loadCityPacks(undefined, { only: values.city });
if (errors.length > 0) {
  for (const { file, message } of errors) console.error(`✗ ${file}: ${message}`);
  process.exit(1);
}

const repo = gh(['repo', 'view', '--json', 'nameWithOwner', '--jq', '.nameWithOwner']);
for (const { city, tilesLock } of packs) {
  const files = await generatedFiles(paths.webTiles, city.slug);
  if (files.length === 0) {
    console.error(`✗ ${city.slug}: nothing to publish; run pnpm data:build -- --city ${city.slug}`);
    process.exit(1);
  }
  const tag = releaseTag(city.slug, new Date());
  const lock = await buildLock(repo, tag, paths.webTiles, files);
  if (tilesLock && JSON.stringify(tilesLock.files) === JSON.stringify(lock.files)) {
    console.log(`✓ ${city.slug}: unchanged since ${tilesLock.tag}; nothing to publish`);
    continue;
  }
  console.log(`▶ ${city.slug}: publishing ${files.join(', ')} as ${tag} in ${repo}`);
  gh([
    'release',
    'create',
    tag,
    ...files.map((name) => join(paths.webTiles, name)),
    '--title',
    `Tiles: ${city.name.en} (${tag.slice(`tiles-${city.slug}-`.length)})`,
    '--notes',
    `Generated by pnpm data:build for ${city.slug}. Pinned by ` +
      `packages/content/cities/${city.slug}/tiles.lock.json.`,
    '--latest=false',
  ]);
  await writeJson(join(contentRoot, 'cities', city.slug, 'tiles.lock.json'), lock, true);
  console.log(`✓ ${city.slug}: wrote cities/${city.slug}/tiles.lock.json; commit it`);
}
