import type { Atlas, EmojiInView } from '@atlas/renderer';
import { act, createElement } from 'react';
import { createRoot } from 'react-dom/client';
import { afterEach, expect, it, vi } from 'vitest';
import { useAtlasInstance } from '@/state/store';
import { useEmojiStore } from '@/state/emoji';
import { CueBubbles } from './CueBubbles';
afterEach(() => {
  useAtlasInstance.setState({ atlas: null });
  vi.restoreAllMocks();
  vi.unstubAllGlobals();
});
it('renders emoji without a dialogue catalog, reads current label footprints and removes disabled nodes', () => {
  vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT', true);
  vi.spyOn(HTMLElement.prototype, 'offsetWidth', 'get').mockReturnValue(38);
  vi.spyOn(HTMLElement.prototype, 'offsetHeight', 'get').mockReturnValue(34);
  let listener: ((cues: EmojiInView[]) => void) | undefined;
  let labels = [{ left: 360, top: 210, width: 80, height: 78 }];
  const on: Atlas['on'] = (event, handler) => {
    if (event === 'emojichange') listener = handler as typeof listener;
    return () => {};
  };
  const getLabelObstacles = vi.fn(() => labels);
  useAtlasInstance.setState({ atlas: { on, getLabelObstacles } as unknown as Atlas });
  useEmojiStore.setState({ enabled: true });
  const container = document.createElement('div');
  document.body.append(container);
  const root = createRoot(container);
  act(() => root.render(createElement(CueBubbles)));
  const cue: EmojiInView = { id: 'dog', subject: 'dog', mood: 'happy', point: [400, 300] };
  act(() => listener!([cue]));
  const node = container.querySelector<HTMLElement>('[data-emoji-bubble]')!;
  expect(node.textContent).toBe('💕');
  expect(node.style.visibility).toBe('visible');
  expect(node.dataset.below).toBe('true');
  labels = [];
  act(() => listener!([{ ...cue, point: [400.1, 300] }]));
  expect(node.dataset.below).toBe('false');
  expect(getLabelObstacles).toHaveBeenCalledTimes(2);
  act(() => useEmojiStore.setState({ enabled: false }));
  expect(container.querySelector('[data-emoji-bubble]')).toBeNull();
  act(() => root.unmount());
  container.remove();
});
